import logging
import os
from pathlib import Path

import pandas as pd
import uvicorn
from fastapi import Body, FastAPI
from igel import Igel
from igel.configs import temp_post_req_data_path

logger = logging.getLogger(__name__)


app = FastAPI()
model = None


@app.get("/")
async def just_for_testing():
    return {"success": True}


@app.post("/predict")
async def predict(data: dict = Body(...)):
    """
    parse json data received from client, use pre-trained model to generate predictions and send them back to client
    """
    try:
        logger.info(f"received data | type: {type(data)}")

        # convert values to list in order to convert it later to pandas dataframe
        data = {
            k: [v] if not isinstance(v, list) else v for k, v in data.items()
        }

        # convert received data to dataframe
        df = pd.DataFrame(data, index=None)
        df.to_csv(temp_post_req_data_path, index=False)

        # use igel to generate predictions
        model_resutls_path = os.environ.get("IGEL_MODEL_RESULTS_PATH")
        logger.info(
            f"reading env variable.. | model_path: {model_resutls_path}"
        )
        if not model_resutls_path:
            logger.warning(
                f"Please provide path to the model_results directory generated by igel using the cli!"
            )
        else:
            model_path = Path(model_resutls_path) / "model.joblib"
            description_file = Path(model_resutls_path) / "description.json"
            prediction_file = Path(model_resutls_path) / "predictions.csv"

            res = Igel(
                cmd="predict",
                data_path=str(temp_post_req_data_path),
                model_path=model_path,
                description_file=description_file,
                prediction_file=prediction_file,
            )

            # remove temp file:
            if os.path.exists(temp_post_req_data_path):
                logger.info(
                    f"removing temporary file: {temp_post_req_data_path}"
                )
                os.remove(temp_post_req_data_path)

            logger.info("sending predictions..")
            print("predictions: ", res.predictions)
            return {"prediction": res.predictions.to_numpy().tolist()}

    except FileNotFoundError as ex:
        logger.exception(ex)
        # remove temp file:
        if os.path.exists(temp_post_req_data_path):
            logger.info(
                f"Exception occured: removing temporary file: {temp_post_req_data_path}"
            )
            os.remove(temp_post_req_data_path)


def run(**kwargs):

    uvicorn.run(app)


if __name__ == "__main__":
    run()
